sonar.projectKey=shelf-book-portfolio
sonar.projectName=shelf-book-portfolio

# Path to the source directories
sonar.sources=src
# Exclude tests and other non-production code from being analyzed as source code
sonar.exclusions=**/*.test.ts,**/*.test.tsx,**/node_modules/**,.next/**

# Path to the test directories
# sonar.tests=__tests__
# sonar.test.inclusions=**/*.test.ts,**/*.test.tsx

# Javascript/Typescript specific
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Encoding of the source code
sonar.sourceEncoding=UTF-8

# SonarCloud specific
sonar.organization=awaluddin-dev
sonar.host.url=https://sonarcloud.io
