sonar.projectKey=shelf-book-portfolio
sonar.projectName=shelf-book-portfolio

# Path to the source directories
sonar.sources=src
# Exclude tests and other non-production code from being analyzed as source code
sonar.exclusions=**/*.test.ts,**/*.test.tsx,**/node_modules/**,.next/**,src/app/globals.css,src/shared/ui/P5Background.tsx

# Path to the test directories
# sonar.tests=__tests__
# sonar.test.inclusions=**/*.test.ts,**/*.test.tsx

# Javascript/Typescript specific
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Encoding of the source code
sonar.sourceEncoding=UTF-8

# SonarCloud specific
sonar.organization=awaluddin-dev
sonar.host.url=https://sonarcloud.io
sonar.cpd.exclusions=**/model/*.ts,src/entities/**/model/*.ts,src/views/admin-*/ui/*.tsx
sonar.coverage.exclusions=src/shared/ui/P5Background.tsx,src/entities/project/ui/ProjectArchitectureDiagram.tsx,src/features/contact/ui/ContactModal.tsx,src/views/testimoni/ui/TestimoniPage.tsx,src/views/admin-*/ui/*.tsx
